#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create 2 Greenhouses
#
curl -iX POST \
  'http://localhost:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  {
  "id": "urn:ngsi-ld:Greenhouse:001",
  "type": "Greenhouse",
  "name": {
      "type": "Text",
      "value": "GreenHouse:001"
  },

  "description": {
      "type": "Text",
      "value": "GreenHouse 1 with rice crop"
  },
  "address": {
      "type": "Property",
      "value": {
          "type": "PostalAddress",
          "addressLocality": "Ismalia",
          "addressCountry": "EG",
          "streetAddress": "Street 123"
      }
  },
  "location": {
      "type": "geo:json",
      "value": {
          "type": "Point",
          "coordinates": [14.12, 55.22]
      }
  }
},
{
"id": "urn:ngsi-ld:Greenhouse:002",
"type": "Greenhouse",
"name": {
    "type": "Text",
    "value": "GreenHouse 2"
},
"description": {
    "type": "Text",
    "value": "GreenHouse 2 with wheat crop"
},

"address": {
    "type": "Property",
    "value": {
        "type": "PostalAddress",
        "addressLocality": "Fayoum",
        "addressCountry": "EG",
        "streetAddress": "Street 456"
    }
},
"location": {
    "type": "geo:json",
    "value": {
        "type": "Point",
        "coordinates": [24.12, 65.22]
    }
}

}
  ]
}'


#
# Create a service group with apikey = 4jggokgpepnvsb2uv4s40d59ov
#
#
curl -iX POST \
'http://localhost:4041/iot/services' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Thing",
     "resource":    "/iot/json"
   }
 ]
}'

#
# Create a series of Sensors.
#
curl -iX POST \
'http://localhost:4041/iot/devices' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
 "devices": [
        {
            "device_id": "soilmoisture001",
            "entity_name": "urn:ngsi-ld:SoilMoisture:001",
            "entity_type": "SoilMoisture",
            "attributes": [
                {
                    "object_id": "sm",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "soilmoisture002",
            "entity_name": "urn:ngsi-ld:SoilMoisture:002",
            "entity_type": "SoilMoisture",
            "attributes": [
                {
                    "object_id": "sm",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "temperature001",
            "entity_name": "urn:ngsi-ld:Temperature:001",
            "entity_type": "Temperature",
            "attributes": [
                {
                    "object_id": "t",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "temperature002",
            "entity_name": "urn:ngsi-ld:Temperature:002",
            "entity_type": "Temperature",
            "attributes": [
                {
                    "object_id": "t",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "humidity001",
            "entity_name": "urn:ngsi-ld:Humidity:001",
            "entity_type": "Humidity",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "humidity002",
            "entity_name": "urn:ngsi-ld:Humidity:002",
            "entity_type": "Humidity",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "light001",
            "entity_name": "urn:ngsi-ld:Light:001",
            "entity_type": "Light",
            "attributes": [
                {
                    "object_id": "l",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "light002",
            "entity_name": "urn:ngsi-ld:Light:002",
            "entity_type": "Light",
            "attributes": [
                {
                    "object_id": "l",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "co2001",
            "entity_name": "urn:ngsi-ld:CO2:001",
            "entity_type": "CO2",
            "attributes": [
                {
                    "object_id": "c",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "co2002",
            "entity_name": "urn:ngsi-ld:CO2:002",
            "entity_type": "CO2",
            "attributes": [
                {
                    "object_id": "c",
                    "name": "count",
                    "type": "Integer"
                }
            ],
            "static_attributes": [
                {
                    "name": "refGreenhouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        }
    ]
}
'


#
# Create a series of Actuators.
#
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "devices": [
        {
            "device_id": "tempbell001",
            "entity_name": "urn:ngsi-ld:TempBell:001",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "tempbell002",
            "entity_name": "urn:ngsi-ld:TempBell:002",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "humiditybell001",
            "entity_name": "urn:ngsi-ld:HumidityBell:001",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "humiditybell002",
            "entity_name": "urn:ngsi-ld:HumidityBell:002",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "co2bell001",
            "entity_name": "urn:ngsi-ld:CO2Bell:001",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "co2bell002",
            "entity_name": "urn:ngsi-ld:CO2Bell:002",
            "entity_type": "Bell",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "sprinkler001",
            "entity_name": "urn:ngsi-ld:Sprinkler:001",
            "entity_type": "Sprinkler",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:001"
                }
            ]
        },
        {
            "device_id": "sprinkler002",
            "entity_name": "urn:ngsi-ld:Sprinkler:002",
            "entity_type": "Sprinkler",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "lamp001",
            "entity_name": "urn:ngsi-ld:Lamp:001",
            "entity_type": "Lamp",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        },
        {
            "device_id": "lamp002",
            "entity_name": "urn:ngsi-ld:Lamp:002",
            "entity_type": "Lamp",
            "protocol": "PDI-IoTA-UltraLight",
            "transport": "HTTP",
            "commands": [
                {
                    "name": "on",
                    "type": "command"
                },
                {
                    "name": "off",
                    "type": "command"
                }
            ],
            "attributes": [
                {
                    "object_id": "s",
                    "name": "state",
                    "type": "Text"
                }
            ],
            "static_attributes": [
                {
                    "name": "refAgrihouse",
                    "type": "Relationship",
                    "value": "urn:ngsi-ld:Greenhouse:002"
                }
            ]
        }
    ]
}
'


#
# Create Registerations for lamps
#
#
curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Lamp Commands",
    "dataProvided": {
        "entities": [
            {
                "id": "urn:ngsi-ld:Lamp:001",
                "type": "Lamp"
            }
        ],
        "attrs": [
            "on",
            "off"
        ]
    },
    "provider": {
        "http": {
            "url": "http://orion:1026/v1"
        },
        "legacyForwarding": true
    }
}'


curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Lamp Commands",
            "dataProvided": {
                "entities": [
                    {
                        "id": "urn:ngsi-ld:Lamp:002",
                        "type": "Lamp"
                    }
                ],
                "attrs": [
                    "on",
                    "off"
                ]
            },
            "provider": {
                "http": {
                    "url": "http://orion:1026/v1"
                },
                "legacyForwarding": true
            }
        }'



#
# Create Registerations for Bells
#
#
curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Bell Commands",
            "dataProvided": {
                "entities": [
                    {
                        "id": "urn:ngsi-ld:Bell:001",
                        "type": "Bell"
                    }
                ],
                "attrs": [
                    "on",
                    "off"
                ]
            },
            "provider": {
                "http": {
                    "url": "http://orion:1026/v1"
                },
                "legacyForwarding": true
            }
        }'

curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Bell Commands",
            "dataProvided": {
                "entities": [
                    {
                        "id": "urn:ngsi-ld:Bell:002",
                        "type": "Bell"
                    }
                ],
                "attrs": [
                    "on",
                    "off"
                ]
            },
            "provider": {
                "http": {
                    "url": "http://orion:1026/v1"
                },
                "legacyForwarding": true
            }
        }'

#
# Create Registerations for Sprinklers
#
#
curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Sprinkler Commands",
            "dataProvided": {
                "entities": [
                    {
                        "id": "urn:ngsi-ld:Sprinkler:001",
                        "type": "Sprinkler"
                    }
                ],
                "attrs": [
                    "on",
                    "off"
                ]
            },
            "provider": {
                "http": {
                    "url": "http://orion:1026/v1"
                },
                "legacyForwarding": true
            }
        }'

curl -iX POST \
'http://localhost:1026/v2/registrations' \
-H 'Content-Type: application/json' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-d '{
    "description": "Sprinkler Commands",
            "dataProvided": {
                "entities": [
                    {
                        "id": "urn:ngsi-ld:Sprinkler:002",
                        "type": "Sprinkler"
                    }
                ],
                "attrs": [
                    "on",
                    "off"
                ]
            },
            "provider": {
                "http": {
                    "url": "http://orion:1026/v1"
                },
                "legacyForwarding": true
            }
        }'

        echo -e " \033[1;32mdone\033[0m"
